In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([1,2,3,4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [4]:
dtype?

Object `dtype` not found.


In [5]:
np.add?

In [6]:
np_int_array = np.array([1,2,3,4])

In [7]:
np_int_array

array([1, 2, 3, 4])

In [8]:
np.append(np_int_array, 5.2)

array([ 1. ,  2. ,  3. ,  4. ,  5.2])

In [9]:
np_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
np_matrix '''this is the way to create numpy matrix'''

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.zeros(10, dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(100, dtype = float)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
np.full((3,5),3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [15]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [17]:
np.linspace(0,1000,125)

array([    0.        ,     8.06451613,    16.12903226,    24.19354839,
          32.25806452,    40.32258065,    48.38709677,    56.4516129 ,
          64.51612903,    72.58064516,    80.64516129,    88.70967742,
          96.77419355,   104.83870968,   112.90322581,   120.96774194,
         129.03225806,   137.09677419,   145.16129032,   153.22580645,
         161.29032258,   169.35483871,   177.41935484,   185.48387097,
         193.5483871 ,   201.61290323,   209.67741935,   217.74193548,
         225.80645161,   233.87096774,   241.93548387,   250.        ,
         258.06451613,   266.12903226,   274.19354839,   282.25806452,
         290.32258065,   298.38709677,   306.4516129 ,   314.51612903,
         322.58064516,   330.64516129,   338.70967742,   346.77419355,
         354.83870968,   362.90322581,   370.96774194,   379.03225806,
         387.09677419,   395.16129032,   403.22580645,   411.29032258,
         419.35483871,   427.41935484,   435.48387097,   443.5483871 ,
      

In [18]:
np.linspace(1,1000,10)

array([    1.,   112.,   223.,   334.,   445.,   556.,   667.,   778.,
         889.,  1000.])

In [19]:
np.linspace(0,1000,11)

array([    1. ,   100.9,   200.8,   300.7,   400.6,   500.5,   600.4,
         700.3,   800.2,   900.1,  1000. ])

In [21]:
np.linspace(100,1000,10)

array([  100.,   200.,   300.,   400.,   500.,   600.,   700.,   800.,
         900.,  1000.])

In [24]:
np.random.random((3,3))

array([[ 0.6990618 ,  0.2944227 ,  0.37150901],
       [ 0.89298092,  0.23574021,  0.51471197],
       [ 0.22432141,  0.4911654 ,  0.37363456]])

In [27]:
np.random.normal(0,1,(3,3)) ''' this is actually mean, SD, and the matrix'''

array([[ 0.49056579, -0.04278202,  0.20347339],
       [ 0.19038809, -0.54506136, -0.93323325],
       [ 0.3075459 , -0.27352398,  0.64814421]])

In [28]:
np.random.normal(0,100,(3,3)) ''' (mean, SD, (matrix indices))'''

array([[ -22.06234139,  -29.2302365 ,  -88.45525153],
       [ -17.34666623,  -27.05753634,  -97.27875732],
       [ 170.6141207 ,   57.46224984, -179.27569509]])

In [29]:
np.random.randint(0,10,(3,3))

array([[2, 4, 4],
       [8, 5, 0],
       [9, 3, 3]])

In [30]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [31]:
np.eye(3) '''Identity matrix - when you multiply any matrix to identity matrix, you get same matrix'''

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [32]:
np.empty(20)'''this gives random value purely based on 20 memory spaces value'''

array([  1.72723371e-077,   1.72723371e-077,   5.92878775e-323,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   2.12199579e-314,
         2.17473548e-314,   1.72723371e-077,   1.72723371e-077,
         3.45845952e-323,   0.00000000e+000,   0.00000000e+000,
         1.72723371e-077,   1.72723371e-077,  -2.68678361e+154,
        -4.33306899e-311,  -1.29073843e-231])

In [33]:
np.empty(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [34]:
np.empty(30)

array([  1.72723371e-077,  -2.68678361e+154,   7.41098469e-323,
         0.00000000e+000,   0.00000000e+000,   2.14027814e+161,
         5.04621383e+180,   4.50618615e-144,   7.79952704e-143,
         4.50605602e-144,   4.27255699e+180,   2.91237123e+257,
         5.56111702e+180,   2.16385138e+190,   2.37682027e+006,
         1.26317419e+006,   6.81286706e+015,   6.81169024e+015,
         4.26221879e-096,   9.08366793e+223,   1.07086311e-037,
         2.74073570e-057,   3.05353922e+030,   6.77462343e-057,
         1.41529402e+161,   9.16651763e-072,   4.10024121e+097,
         3.31787451e-033,   7.75957852e-144,   2.11653000e-308])

In [35]:
x3 = np.random.randint(10, size=(3,4,5))

In [36]:
print ("x3 ndim:", x3.ndim) ''' Gives the dimension of the matrix'''

('x3 ndim:', 3)


In [37]:
print("x3 shape:", x3.shape) ''' Gives the matrix size - it is axis'''

('x3 shape:', (3, 4, 5))


In [38]:
print("x3 size", x3.size) ''' Gives the length of eqv - it is number of element'''

('x3 size', 60)


In [39]:
x3.dtype ''' this gives the data type of the np array'''

dtype('int64')

In [40]:
x3.itemsize '''this gives the each minimum '''

8

In [41]:
x3.nbytes

480

In [43]:
import sys

In [44]:
x3

array([[[2, 7, 5, 7, 1],
        [6, 0, 4, 7, 1],
        [5, 7, 9, 0, 4],
        [6, 2, 0, 1, 3]],

       [[3, 2, 1, 3, 7],
        [2, 3, 4, 6, 6],
        [3, 5, 7, 3, 5],
        [8, 7, 9, 2, 9]],

       [[6, 5, 0, 6, 1],
        [4, 0, 4, 9, 5],
        [9, 4, 6, 7, 5],
        [2, 4, 6, 1, 5]]])

In [45]:
x3[2][1][1]

0

In [46]:
x3[2,2]

array([9, 4, 6, 7, 5])

In [47]:
x3[2]

array([[6, 5, 0, 6, 1],
       [4, 0, 4, 9, 5],
       [9, 4, 6, 7, 5],
       [2, 4, 6, 1, 5]])

In [49]:
x3[-1]

array([[6, 5, 0, 6, 1],
       [4, 0, 4, 9, 5],
       [9, 4, 6, 7, 5],
       [2, 4, 6, 1, 5]])

In [50]:
x3[-1][-2]

array([9, 4, 6, 7, 5])

In [51]:
x = np.arange(10)

In [53]:
x[0:8:2] ''' this shows the slicing in the np array'''

array([0, 2, 4, 6])

x2 = np.random.randint(10, size = (3,4))

In [57]:
x2 = np.random.randint(10, size = (3,4))

In [58]:
x2

array([[9, 4, 1, 2],
       [0, 8, 5, 3],
       [9, 6, 7, 0]])

In [59]:
x2[:2, :3]

array([[9, 4, 1],
       [0, 8, 5]])

In [60]:
x2[:3,::2]

array([[9, 1],
       [0, 5],
       [9, 7]])

In [61]:
x2[::2,1:] ''' every axis start:end:jump'''

array([[4, 1, 2],
       [6, 7, 0]])

In [64]:
list_ = np.arange(1,9)

In [65]:
list_

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
list_.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
list_.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [68]:
list_.reshape(list_.shape)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
list_.reshape(list_.shape)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
x = np.array([1,2,3])

In [71]:
y = np.array([1,2,3])

In [72]:
np.concatenate([x,y])

array([1, 2, 3, 1, 2, 3])

In [75]:
y = np.array([[99],
             [99]])

In [76]:
y.shape

(2, 1)

In [77]:
y = np.array([[99],[99]])

In [78]:
y.shape

(2, 1)

In [79]:
grid = np.array([[9,8,7],[6,5,4]])

In [80]:
y = np.array([[99],
             [99]])

In [81]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [82]:
z=np.array([[100,101],[100,101]])

In [83]:
np.hstack([grid,y,z])

array([[  9,   8,   7,  99, 100, 101],
       [  6,   5,   4,  99, 100, 101]])