In [2]:
import numpy as np

In [20]:
''' Partioning'''
x = np.array([5,4,3,2,1])

In [21]:
np.partition(x,3)

array([2, 1, 3, 4, 5])

In [22]:
np.partition(x,2)

array([1, 2, 3, 4, 5])

In [23]:
y = np.array([10,2,30,4,50,6])

In [24]:
np.partition(y,5)

array([ 4,  6,  2, 10, 30, 50])

In [25]:
np.partition(y,3)

array([ 4,  6,  2, 10, 50, 30])

In [27]:
'''this is partial sorting - partitioning'''