In [4]:
'''Numpy : Structured Arrays'''
import numpy as np

In [2]:
name = ['Alice' , 'Bob','Cathy','James']

In [3]:
age = [25, 45, 36, 18]
weight = [10,20,30,50]

In [11]:
data = np.zeros( 4, dtype = {'names': ('name', 'age','weight'),
                             'formats': ( 'U10', 'i4', 'f8')})

In [8]:
data

array([(u'', 0, 0.0), (u'', 0, 0.0), (u'', 0, 0.0), (u'', 0, 0.0)], 
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [9]:
example = np.zeros( 4, dtype = list)

In [10]:
example

array([0, 0, 0, 0], dtype=object)

In [12]:
''' in the data example we gave data type as custom structered  with above data type with different elements'''

' in the data example we gave data type as custom structered  with above data type with different elements'

In [17]:
data2 = np.zeros(4, dtype = {'names' : ('school', 'students'),
                             'formats' : ('int', 'int')})

In [24]:
data2 = np.zeros(4, dtype = {'names' : ('school', 'students'),
                             'formats' : ('str', 'int')})

TypeError: data type not understood

In [19]:
np.str_

numpy.string_

In [34]:
data2 = np.zeros(4, dtype = {'names' : ('school', 'students'),
                             'formats' : ('U1', 'int')}) 
''' instead of string for python 2 string must be represetned as U'''

' instead of string for python 2 string must be represetned as U'

In [35]:
data2

array([(u'', 0), (u'', 0), (u'', 0), (u'', 0)], 
      dtype=[('school', '<U1'), ('students', '<i8')])

In [36]:
data = np.zeros( 4, dtype = {'names': ('name', 'age','weight'),
                             'formats': ( 'U10', 'i4', 'f8')})

In [37]:
data

array([(u'', 0, 0.0), (u'', 0, 0.0), (u'', 0, 0.0), (u'', 0, 0.0)], 
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [38]:
name, age , weight

(['Alice', 'Bob', 'Cathy', 'James'], [25, 45, 36, 18], [10, 20, 30, 50])

In [39]:
data['name'] = name
data['age'] = age
data['weight'] = weight

In [40]:
data

array([(u'Alice', 25, 10.0), (u'Bob', 45, 20.0), (u'Cathy', 36, 30.0),
       (u'James', 18, 50.0)], 
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [41]:
type(data)

numpy.ndarray

In [42]:
data.size

4

In [43]:
data.shape

(4,)

In [44]:
data.itemsize

52

In [45]:
data[0]

(u'Alice', 25, 10.0)

In [46]:
print data[0]

(u'Alice', 25, 10.0)


In [47]:
data[-1]['name']

u'James'

In [48]:
data[data['age'] < 30]['name'] ''' this is like boolean masking for finding all the names with age less than 30'''

array([u'Alice', u'James'], 
      dtype='<U10')

In [49]:
''' above exampe can be used for president example for find the max and min height'''

' above exampe can be used for president example for find the max and min height'

In [50]:
'''Defining Numpy "Structred Arrays "using " dictionary method" '''
data = np.zeros( 4, dtype = {'names': ('name', 'age','weight'),
                             'formats': ( 'U10', 'i4', 'f8')})

In [61]:
''' Defining Numpy "Structure Arrays" using " list of tuple method"'''
my_type1 = np.dtype([('name', 'U10'),('age','<i8'),('weight','f8')])

In [64]:
my_type2 = np.dtype('U10, i8, f8')
''' This is also another method to define the numpy structure array, but can be accessed only with index'''

' This is also another method to define the numpy structure array, but can be accessed only with index'

In [59]:
''' Defining Numpy Advance " Structured Arrays"'''
my_type3 = np.dtype ([('id','i8'), ('mat','f8',(3,3))])

In [60]:
my_type3

dtype([('id', '<i8'), ('mat', '<f8', (3, 3))])

In [66]:
data2 = np.zeros(4, dtype = my_type2)

In [67]:
data3 = np.zeros(4, dtype = my_type3)

In [68]:
'''Defining Numpy "Record Arrays" 
   Records Arrays are structred arrays, where fields can be accessed as attributes rather than dictionary keys'''
data['age']

array([0, 0, 0, 0], dtype=int32)

In [69]:
''' data_rec is now a "Record Array" made up from the "Structed Array" data
    Every "STructred Array" has a .view() function that returns a "Recod Array"
    when it is given the "recarry" argument '''
data_rec = data.view(np.recarray)

In [70]:
''' Instead of data_rec['age'], you do: '''
data_rec.age

array([0, 0, 0, 0], dtype=int32)