In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
''' create a function a called make_def
    make_def takes two parameters cols and ind
    cols specify the column headers as a string where every column header has only one letter
    ind specify the rows as an integer
    For eg: make_def('ABC',range(3)) should return 
      A  B  C
    0 A0 B0 C0
    1 A1 B1 C1
    2 A2 B2 C2
'''

" create a function a called make_def\n    make_def takes two parameters cols and ind\n    cols specify the column headers as a string where every column header has only one letter\n    ind specify the rows as an integer\n    For eg: make_def('ABC',range(3)) should return \n      A  B  C\n    0 A0 B0 C0\n    1 A1 B1 C1\n    2 A2 B2 C2\n"

In [13]:
def make_def(cols,ind):
    data = {c:[str(c) + str(i) for i in ind for c in cols]}
    return pd.DataFrame(data,ind)

In [8]:
[str(x)+str(y) for x in range(3) for y in range(3)]

['00', '01', '02', '10', '11', '12', '20', '21', '22']

In [15]:
def make_def(cols,ind):
    data = {c:[str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data,ind)

In [16]:
make_def('ABC',range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [19]:
data = {c:[str(c) + str(i) for i in'ABC'] for c in [1,2,3]}

In [20]:
data

{1: ['1A', '1B', '1C'], 2: ['2A', '2B', '2C'], 3: ['3A', '3B', '3C']}

In [21]:
x = range(1,4)

In [22]:
y = range(4,7)

In [23]:
z = range(7,10)

In [24]:
x,y,z

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [26]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x = [[1,2],
     [3,4]]

In [29]:
np.concatenate([x,x],axis = 1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [30]:
np.concatenate([x,x],axis = 0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [31]:
pd.concat?

In [33]:
s1 = pd.Series(['A','B','C'], index = [1,2,3])
s2 = pd.Series(['D','E','F'], index = [4,5,6])

In [35]:
pd.concat([s1,s2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [39]:
df1 = make_def('AB',[1,2])
df2 = make_def('AB',[3,4])

In [40]:
df1,df2,pd.concat([df1,df2])

(    A   B
 1  A1  B1
 2  A2  B2,     A   B
 3  A3  B3
 4  A4  B4,     A   B
 1  A1  B1
 2  A2  B2
 3  A3  B3
 4  A4  B4)

In [41]:
df1

A   B
1  A1  B1
2  A2  B2

In [42]:
df2

A   B
3  A3  B3
4  A4  B4

In [43]:
pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [44]:
''' concat is always stacking'''

' concat is always stacking'

In [46]:
pd.concat([df1,df2], axis = 0)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [47]:
pd.concat([df1,df2], axis = 1)

A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

In [49]:
df3 = make_def('AB',[0,1])
df4 = make_def('CD',[0,1])
df3

A   B
0  A0  B0
1  A1  B1

In [50]:
df4

C   D
0  C0  D0
1  C1  D1

In [52]:
pd.concat([df3,df4],axis = 1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [53]:
pd.concat([df3,df4],axis = 0)

A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1

In [54]:
df5 = make_def('ABC',[1,2])

In [55]:
df6 = make_def('BCD',[3,4])

In [56]:
df5

A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [57]:
df6

B   C   D
3  B3  C3  D3
4  B4  C4  D4

In [59]:
pd.concat([df5,df6])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [60]:
pd.concat([df5,df6], join = 'inner') ''' by this way you concatenate only common items which has full set of data'''

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [63]:
pd.concat([df5,df6],join_axes=[df5.columns]) ''' same joining but only the axis from A,B,C '''

A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [64]:
df1.append(df2) ''' this is almost like concatenation but gives this as DataFrame wheras the concat it only joins'''

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4